# Generated by Django 4.1.3 on 2022-12-23 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_traineeteam_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeteam',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='main.team'),
        ),
    ]
