# Generated by Django 4.1.3 on 2023-01-04 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_traineeteam_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='players', to='main.team', verbose_name='команда'),
        ),
        migrations.AlterField(
            model_name='team',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.stadium', verbose_name='стадион'),
        ),
        migrations.DeleteModel(
            name='TraineeTeam',
        ),
    ]
